FROM mysql:latest

ARG MYSQL_DATABASE
ARG MYSQL_ROOT_PASSWORD
ARG MYSQL_PASSWORD
ARG MYSQL_USER

ENV MYSQL_DATABASE=${MYSQL_DATABASE:-prova}
ENV MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
ENV MYSQL_PASSWORD=${MYSQL_PASSWORD:-passwordMatteo}
ENV MYSQL_USER=${MYSQL_USER:-matteo}

# EXPOSE 3306/tcp
CMD  docker build -t nonloso .